# Generated by Django 3.0.2 on 2020-01-26 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=50)),
                ('campaigns', models.CharField(max_length=50)),
                ('schedule_start', models.DateTimeField(auto_now_add=True)),
                ('schedule_stop', models.DateTimeField(auto_now_add=True)),
                ('impressions', models.IntegerField(blank=True, default=1)),
                ('clicks', models.IntegerField(blank=True, default=1)),
                ('spend', models.IntegerField(blank=True, default=1)),
                ('eCPM', models.IntegerField(blank=True, default=1)),
                ('eCPC', models.IntegerField(blank=True, default=1)),
                ('installs', models.IntegerField(blank=True, default=1, null=True)),
                ('eCPI', models.IntegerField(blank=True, default=1)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
