# Generated by Django 3.0.2 on 2020-01-27 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campgathereddata',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='campgathereddata',
            name='impressions',
        ),
        migrations.RemoveField(
            model_name='campgathereddata',
            name='installs',
        ),
        migrations.RemoveField(
            model_name='campgathereddata',
            name='schedule_start',
        ),
        migrations.RemoveField(
            model_name='campgathereddata',
            name='schedule_stop',
        ),
        migrations.RemoveField(
            model_name='campgathereddata',
            name='spend',
        ),
        migrations.RemoveField(
            model_name='campgathereddata',
            name='status',
        ),
        migrations.AddField(
            model_name='campgathereddata',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campgathereddata',
            name='metric',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campgathereddata',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
