# Generated by Django 3.0.2 on 2020-01-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=50)),
                ('campaigns', models.CharField(max_length=50)),
                ('schedule_start', models.DateTimeField()),
                ('schedule_stop', models.DateTimeField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('spend', models.IntegerField()),
                ('eCPM', models.IntegerField()),
                ('eCPC', models.IntegerField()),
                ('installs', models.IntegerField()),
                ('eCPI', models.IntegerField()),
                ('action', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
