# Generated by Django 3.0.2 on 2020-01-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_auto_20200126_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campdata',
            name='clicks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='campdata',
            name='eCPC',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='campdata',
            name='eCPI',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='campdata',
            name='eCPM',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='campdata',
            name='impressions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='campdata',
            name='installs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='campdata',
            name='spend',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
