# Generated by Django 3.0.2 on 2020-01-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_auto_20200126_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampGatheredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=50)),
                ('schedule_start', models.TimeField(blank=True)),
                ('schedule_stop', models.TimeField(blank=True)),
                ('impressions', models.IntegerField(blank=True, default=0)),
                ('clicks', models.IntegerField(blank=True, default=0)),
                ('spend', models.IntegerField(blank=True, default=0)),
                ('installs', models.IntegerField(blank=True, default=0)),
                ('status', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
